name: fluui_chakra
description: "A flutter chakra ui library"
version: 0.0.1
homepage: https://github.com/fluui-dev/fluui_chakra

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icon_font_generator: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_opsz_wght.ttf
        - asset: fonts/Inter-Italic-VariableFont_opsz_wght.ttf
          style: italic
    - family: Noto
      fonts:
        - asset: fonts/NotoSans-VariableFont_wdth,wght.ttf
        - asset: fonts/NotoSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
    - family: Flutter ChakraUI Icons
      fonts:
        - asset: icons/fluui_icons.otf

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

