name: widgetbook_workspace
description: "fluui widgetbook"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0
  fluui_chakra:
    path: ../../packages/fluui_chakra

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: ../../packages/fluui_chakra/fonts/Inter-VariableFont_opsz_wght.ttf
    - family: Noto
      fonts:
        - asset: ../../packages/fluui_chakra/fonts/NotoSans-VariableFont_wdth,wght.ttf
    - family: Flutter ChakraUI Icons
      fonts:
        - asset: ../../packages/fluui_chakra/icons/fluui_icons.otf
